"""add table vaccination

Revision ID: 3e1304bd92ec
Revises: ef3465d748e5
Create Date: 2022-02-11 16:25:42.615204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e1304bd92ec'
down_revision = 'ef3465d748e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_cards',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_shot_date', sa.DateTime(), nullable=True),
    sa.Column('second_shot_date', sa.DateTime(), nullable=True),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('health_unit_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.drop_table('salgados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salgados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='salgados_pkey'),
    sa.UniqueConstraint('nome', name='salgados_nome_key')
    )
    op.drop_table('vaccine_cards')
    # ### end Alembic commands ###
